# Generated by Django 5.0.3 on 2024-04-08 05:06

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceremo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='iid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=22, max_length=30, prefix='', unique=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=22, max_length=30, prefix='', unique=True),
        ),
    ]
