# Generated by Django 5.0.3 on 2024-04-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceremo_app', '0002_item_iid_vendor_vid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='status',
        ),
        migrations.AddField(
            model_name='item',
            name='available_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='max_rental_duration',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='item',
            name='min_rental_duration',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
