# Generated by Django 5.0.3 on 2024-04-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceremo_app', '0003_remove_item_status_item_available_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='cover_image',
            field=models.ImageField(default='default.jpg', upload_to='user_directory_path'),
        ),
    ]
