# Generated by Django 5.0.3 on 2024-04-09 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceremo_app', '0004_vendor_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock_count',
            field=models.CharField(default=200, max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.60 m', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, default='4.00 m', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='max_rental_duration',
            field=models.IntegerField(default='30 Days '),
        ),
        migrations.AlterField(
            model_name='item',
            name='min_rental_duration',
            field=models.IntegerField(default='1 day'),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, default='5.60 kg', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, default='3.00 m', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='itemimages',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='i_images', to='ceremo_app.item'),
        ),
    ]
