# Generated by Django 5.0.3 on 2024-04-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceremo_app', '0005_item_stock_count_alter_item_height_alter_item_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.60m', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, default='4.00m', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, default='5.60kg', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, default='3.00m', max_digits=10, null=True),
        ),
    ]
