# Generated by Django 5.0.3 on 2024-04-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceremo_app', '0006_alter_item_height_alter_item_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a description of the Item  goes here .'),
        ),
    ]
