# Generated by Django 5.0.3 on 2024-04-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceremo_app', '0007_alter_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='height',
            field=models.CharField(blank=True, default='0.60m', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='length',
            field=models.CharField(blank=True, default='4.00m', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='max_rental_duration',
            field=models.CharField(default='30 Days ', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='min_rental_duration',
            field=models.CharField(default='1 day', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.CharField(blank=True, default='5.60kg', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='width',
            field=models.CharField(blank=True, default='3.00m', max_length=50, null=True),
        ),
    ]
