# Generated by Django 5.0.3 on 2024-04-15 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceremo_app', '0010_tag_alter_item_description_alter_item_specifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemreview',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='ceremo_app.item'),
        ),
    ]
